name: dynamic_value
description: The easy way to work with JSON data, safe access to nested data in the Map and safe type conversion.
version: 3.0.0
author: Andy Chentsov
homepage: https://github.com/andyduke/dynamic_value
repository: https://github.com/andyduke/dynamic_value
issue_tracker: https://github.com/andyduke/dynamic_value/issues

environment:
  sdk: ^3.1.0

dependencies:
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
